- name: Setup Web Server
  hosts: all
  become: true

  tasks:
  - name: Update and ugrade the dependencies repository
    apt:
      update_cache: yes
      upgrade: yes

  - name: Install apache
    apt:
      name:
        - apache2
      state: latest

  - name: Set timezone to Africa/Lagos
    timezone: name=Africa/Lagos

  - name: Display hostname of server
    shell: echo "<h1>Welcome! This is my server name $(hostname -f)</h1>" > /var/www/html/index.html

  - name: restart apache
    service:
      name: apache2
      state: restarted
